export const MAX_WORKFLOW_ID_LENGTH = 128;
export const MAX_WORKFLOW_NAME_LENGTH = 120;
export const MAX_WORKFLOW_DESCRIPTION_LENGTH = 2_000;
export const MAX_GENERATED_STEP_NAME_LENGTH = 160;
export const MAX_GENERATED_IDENTIFIER_LENGTH = 80;
export const MAX_CONVERSION_ISSUES = 4_000;
