export const RUNNER_SERVICE_ERROR_CODES = [
  'RUNNER_SERVICE_CONFIGURATION_INVALID',
  'RUNNER_SERVICE_PLATFORM_UNSUPPORTED',
  'RUNNER_SERVICE_MANAGER_UNAVAILABLE',
  'RUNNER_SERVICE_OPERATION_FAILED',
  'RUNNER_SERVICE_VERIFICATION_FAILED',
  'RUNNER_INSTANCE_ALREADY_ACTIVE',
  'RUNNER_INSTANCE_LOCK_UNAVAILABLE',
  'RUNNER_RUNTIME_TRANSITION_INVALID',
  'RUNNER_RUNTIME_REVOKED',
  'RUNNER_RECONNECT_ABORTED',
  'RUNNER_DRAIN_TIMED_OUT',
  'NATIVE_PROTECTOR_UNAVAILABLE',
  'NATIVE_PROTECTOR_BINDING_INVALID',
  'NATIVE_PROTECTOR_PROTECT_FAILED',
  'NATIVE_PROTECTOR_UNPROTECT_FAILED',
  'NATIVE_PROTECTOR_MIGRATION_FAILED',
] as const;

export type RunnerServiceErrorCode = (typeof RUNNER_SERVICE_ERROR_CODES)[number];

export class RunnerServiceRuntimeError extends Error {
  constructor(readonly code: RunnerServiceErrorCode) {
    super(code);
    this.name = 'RunnerServiceRuntimeError';
  }
}
