export const WORKFLOW_VERIFICATION_SCHEMA_VERSION = 1;
export const VERIFICATION_POLL_INTERVAL_MS = 100;
export const MAX_VERIFICATION_URL_LENGTH = 2_048;
export const MAX_VERIFICATION_TEXT_LENGTH = 4_096;
export const MAX_VERIFICATION_FIELD_VALUE_LENGTH = 4_096;
export const MAX_VERIFICATION_ATTEMPTS = 10_000;
