export const MAX_RECORDING_EVENTS = 1_000;
export const MAX_RECORDING_BATCH_EVENTS = 100;
export const MAX_INPUT_VALUE_LENGTH = 2_048;
export const MAX_CONTROL_VALUE_LENGTH = 512;
export const MAX_TARGET_METADATA_LENGTH = 160;
export const MAX_TEXT_PREVIEW_LENGTH = 120;
export const MAX_CLIENT_BATCH_ID_LENGTH = 128;
export const MAX_RECORDING_ORIGIN_LENGTH = 512;
