export const WORKFLOW_INPUTS_SCHEMA_VERSION = 1;
export const MAX_SECRET_REFERENCE_NAME_LENGTH = 80;
export const MAX_RUNTIME_STRING_LENGTH = 10_000;
export const MAX_RUNTIME_FILE_SIZE_BYTES = 10 * 1024 * 1024 * 1024;
export const MAX_RUNTIME_MEDIA_TYPE_LENGTH = 128;
