export const RUNNER_ACQUISITION_SCHEMA_VERSION = 1 as const;

export const MAX_RELEASE_MANIFEST_BYTES = 256 * 1024;
export const MAX_RELEASE_SIGNATURE_BYTES = 16 * 1024;
export const MAX_RELEASE_ARTIFACT_BYTES = 4 * 1024 * 1024 * 1024;
export const MAX_RELEASE_CACHE_ENTRIES = 16;

export const DEFAULT_RELEASE_CONNECT_TIMEOUT_MS = 10_000;
export const DEFAULT_RELEASE_READ_TIMEOUT_MS = 30_000;
export const DEFAULT_RELEASE_METADATA_TIMEOUT_MS = 60_000;
export const DEFAULT_RELEASE_ARTIFACT_TIMEOUT_MS = 30 * 60 * 1_000;
